// import { TicketList } from "./ticket";


// export const tickets: TicketList[] = [
//   {
//     id: 1,
//     name: 'Package',
//     destination: 'Paris',
//     duration: '7 days',
//     hotels: 'Hotel Paris',
//     date: '2023-05-01',
//     nbOfSeats: 10,
//     source: 'Lebanon',
//     cost: '150 $',
//     sell: '180 $',
//     netprofit: '30 $',
//     note: 'Note',
//     status: 'inprogress'
//   },
//   {
//     id: 2,
//     name: 'Package',
//     destination: 'London',
//     duration: '5 days',
//     hotels: 'Hotel London',
//     date: '2023-06-15',
//     nbOfSeats: 8,
//     source: 'Lebanon',
//     cost: '150 $',
//     sell: '180 $',
//     netprofit: '30 $',
//     note: 'Note',
//     status: 'completed'
//   },
//   {
//     id: 3,
//     name: 'Package',
//     destination: 'New York',
//     duration: '10 days',
//     hotels: 'Hotel New York',
//     date: '2023-07-22',
//     nbOfSeats: 12,
//     source: 'Lebanon',
//     cost: '150 $',
//     sell: '180 $',
//     netprofit: '30 $',
//     note: 'Note',
//     status: 'completed'
//   },
//   {
//     id: 4,
//     name: 'Package',
//     destination: 'Tokyo',
//     duration: '6 days',
//     hotels: 'Hotel Tokyo',
//     date: '2023-08-10',
//     nbOfSeats: 15,
//     source: 'Lebanon',
//     cost: '150 $',
//     sell: '180 $',
//     netprofit: '30 $',
//     note: 'Note',
//     status: 'inprogress'
//   },
//   {
//     id: 5,
//     name: 'Package',
//     destination: 'Sydney',
//     duration: '8 days',
//     hotels: 'Hotel Sydney',
//     date: '2023-09-01',
//     nbOfSeats: 20,
//     source: 'Lebanon',
//     cost: '150 $',
//     sell: '180 $',
//     netprofit: '30 $',
//     note: 'Note',
//     status: 'cancelled'
//   },
//   {
//     id: 6,
//     name: 'Package',
//     destination: 'Rome',
//     duration: '4 days',
//     hotels: 'Hotel Rome',
//     date: '2023-10-15',
//     nbOfSeats: 5,
//     source: 'Lebanon',
//     cost: '150 $',
//     sell: '180 $',
//     netprofit: '30 $',
//     note: 'Note',
//     status: 'completed'
//   },
//   {
//     id: 7,
//     name: 'Package',
//     destination: 'Berlin',
//     duration: '9 days',
//     hotels: 'Hotel Berlin',
//     date: '2023-11-05',
//     nbOfSeats: 7,
//     source: 'Lebanon',
//     cost: '150 $',
//     sell: '180 $',
//     netprofit: '30 $',
//     note: 'Note',
//     status: 'completed'
//   },
//   {
//     id: 8,
//     name: 'Package',
//     destination: 'Moscow',
//     duration: '12 days',
//     hotels: 'Hotel Moscow',
//     date: '2023-12-20',
//     nbOfSeats: 10,
//     source: 'Lebanon',
//     cost: '150 $',
//     sell: '180 $',
//     netprofit: '30 $',
//     note: 'Note',
//     status: 'completed'
//   },
//   {
//     id: 9,
//     name: 'Package',
//     destination: 'Dubai',
//     duration: '7 days',
//     hotels: 'Hotel Dubai',
//     date: '2024-01-14',
//     nbOfSeats: 18,
//     source: 'Lebanon',
//     cost: '150 $',
//     sell: '180 $',
//     netprofit: '30 $',
//     note: 'Note',
//     status: 'inprogress'
//   },
//   {
//     id: 10,
//     name: 'Package',
//     destination: 'Barcelona',
//     duration: '5 days',
//     hotels: 'Hotel Barcelona',
//     date: '2024-02-18',
//     nbOfSeats: 12,
//     source: 'Lebanon',
//     cost: '150 $',
//     sell: '180 $',
//     netprofit: '30 $',
//     note: 'Note',
//     status: 'cancelled'
//   }
// ];